<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Goeduhub/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment/Task 3**

# Reg No.:-**GO_STP_7205**

## Name: **MADHURIMA PAUL**

# Date:- **27/05/2021**

**1.Import the numpy package under the name np and Print the numpy version and the configuration**

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


**2.Create a null vector of size 10**

In [5]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**3.Create Simple 1-D array and check type and check data types in array**

In [8]:
import numpy as np
a = np.array([1, 2, 3])   
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


**4.How to find number of dimensions, bytes per element and bytes of memory used?**

In [9]:
import numpy as np
  
# create a numpy 1d-array
x = np.array([100,20,34])
  
print("Size of the array: ",x.size)
  
print("Memory size of one array element in bytes: ",x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",x.size * x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24


**5.Create a null vector of size 10 but the fifth value which is 1**

In [10]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**6.Create a vector with values ranging from 10 to 49**

In [11]:
import numpy as np
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


**7.Reverse a vector (first element becomes last)**

In [12]:
import numpy as np
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


**8.Create a 3x3 matrix with values ranging from 0 to 8**

In [13]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**9.Find indices of non-zero elements from [1,2,0,0,4,0]**

In [14]:
import numpy as np
nums = np.array([1,2,0,0,4,0])
print("Original array:")
print(nums)
print("Indices of elements equal to zero of the said array:")
result = np.where(nums == 0)[0]
print(result)

Original array:
[1 2 0 0 4 0]
Indices of elements equal to zero of the said array:
[2 3 5]


**10.Create a 3x3 identity matrix**

In [15]:
import numpy as np
array_2D=np.eye(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**11.Create a 3x3x3 array with random values**

In [17]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.45776165 0.53799649 0.91835319]
  [0.94865951 0.14804791 0.53482359]
  [0.77895079 0.34128469 0.9241496 ]]

 [[0.39589138 0.3287014  0.11073461]
  [0.890634   0.03260323 0.288631  ]
  [0.28010134 0.57465188 0.80220659]]

 [[0.3752881  0.91091926 0.15647011]
  [0.52309666 0.11335948 0.46824774]
  [0.92280365 0.03055672 0.1253142 ]]]


**12.Create a 10x10 array with random values and find the minimum and maximum values**

In [18]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.34794213 0.92569316 0.31355951 0.83769566 0.43097921 0.88398369
  0.91731741 0.00308535 0.1066398  0.12317291]
 [0.98311735 0.79496856 0.40705488 0.85804576 0.68063882 0.91706294
  0.75226002 0.00989712 0.98953891 0.08945412]
 [0.60504035 0.85899907 0.63796156 0.3210729  0.54162525 0.8816938
  0.47728458 0.67972172 0.49196709 0.70757657]
 [0.14856811 0.40329163 0.59161451 0.0359816  0.67309251 0.5178118
  0.12107147 0.74124677 0.27433548 0.83694789]
 [0.32962193 0.57332352 0.4037635  0.0689339  0.9142608  0.94910668
  0.19583882 0.4979275  0.93933187 0.53266309]
 [0.84776692 0.01065652 0.69360831 0.31930914 0.7646452  0.34608874
  0.50319065 0.15383097 0.91624112 0.49600102]
 [0.88953011 0.73950334 0.92892502 0.07065077 0.59230586 0.74612826
  0.70408748 0.18378602 0.39854033 0.03479776]
 [0.62657012 0.7356536  0.99062706 0.82702705 0.41212515 0.55546047
  0.61902053 0.04930284 0.33532432 0.70895468]
 [0.47199474 0.30948025 0.05288047 0.10391617 0.55788672 0.7661219

**13.Create a random vector of size 30 and find the mean value**

In [19]:
import numpy as np
x = np.random.random(30)
print(x)
print(np.mean(x))

[0.2483545  0.00634425 0.10599477 0.94035593 0.79205184 0.67759225
 0.05996812 0.30320268 0.60428567 0.30533802 0.09759569 0.44690617
 0.7536442  0.89108089 0.58076039 0.59199679 0.30080231 0.27030726
 0.78365369 0.86952968 0.35355998 0.04840383 0.23515973 0.2292175
 0.40656432 0.92161759 0.70495139 0.98779901 0.49254406 0.86290798]
0.4957496830676108


**14.Create a 2d array with 1 on the border and 0 inside**

In [20]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**15.How to add a border (filled with 0's) around an existing array?**

In [21]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?**

**Example -**
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]] 

**Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20**

In [22]:
import numpy as np
Arr= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(Arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
print(Arr[1,5])

13


In [48]:
print(Arr[0,:])

[1 2 3 4 5 6 7]


In [32]:
print(Arr[:,2])

[ 3 10]


In [51]:
print(Arr[0,:][1:6:2])

[2 4 6]


In [52]:
Arr[1,5]=20
print(Arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


**17.How to Convert a 1D array to a 2D array with 2 rows**



In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = arr.reshape(2, 3)

print(newarr)

[[1 2 3]
 [4 5 6]]


**18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.**

**Input:**

**a = np.array([1,2,3])**

**Desired Output:**

**#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])**

In [55]:
import numpy as np
a=np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


**19.Write a program to show how Numpy taking less memory compared to Python List?**

In [56]:
import numpy as np
  
# importing system module
import sys
  
# declaring a list of 1000 elements 
S= range(1000)
  
# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))
  
# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
  
# declaring a Numpy array of 1000 elements 
D= np.arange(1000)
  
# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
  
# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


**20.Write a program to show how Numpy taking less time compared to Python List?**

In [57]:
import numpy
import time
   
# size of arrays and lists
size = 1000000  
   
# declaring lists
list1 = range(size)
list2 = range(size)
   
# declaring arrays
array1 = numpy.arange(size)  
array2 = numpy.arange(size)
   
# capturing time before the multiplication of Python lists
initialTime = time.time()
  
# multiplying  elements of both the lists and stored in another list
resultantList = [(a * b) for a, b in zip(list1, list2)]
   
# calculating execution time
print("Time taken by Lists to perform multiplication:", 
      (time.time() - initialTime),
      "seconds")
   
# capturing time before the multiplication of Numpy arrays
initialTime = time.time()
  
# multiplying  elements of both the Numpy arrays and stored in another Numpy array 
resultantArray = array1 * array2
   
# calculating execution time 
print("Time taken by NumPy Arrays to perform multiplication:",
      (time.time() - initialTime),
      "seconds")

Time taken by Lists to perform multiplication: 0.13798308372497559 seconds
Time taken by NumPy Arrays to perform multiplication: 0.005174160003662109 seconds
